apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app-deployment
  namespace: default   # Specify your desired namespace here
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
        - name: my-node-app-container
          image: your-docker-hub-username/node-app:latest
          ports:
            - containerPort: 3000


